In [14]:
import numpy as np

X_train = np.array([[0.0, 0.0], [1.0,1.0], [5.0, 5.0], [6.0,6.0]])
y_train = np.array([0, 0, 1, 1])
x = np.array([5.5, 5.5])

In [15]:
diffs = X_train - x
print(f"differences: \n{diffs}")

differences: 
[[-5.5 -5.5]
 [-4.5 -4.5]
 [-0.5 -0.5]
 [ 0.5  0.5]]


In [16]:
dists = np.linalg.norm(diffs, axis=1)
print(dists)

[7.77817459 6.36396103 0.70710678 0.70710678]


In [24]:
sorted_idx = np.argsort(dists)
print(sorted_idx)

[3 2 1 0]


In [41]:
k = 1
nearest_idx = sorted_idx[:k]
nearest_labels = y_train[nearest_idx]
prediction = np.bincount(nearest_labels).argmax()
print(prediction)
print(nearest_labels)



1
[1]


In [43]:
def predict_one(X_train, y_train, x, k):
    diffs = X_train - x
    dists = np.linalg.norm(diffs, axis=1)
    sorted_idx = np.argsort(dists)
    nearest_idx = sorted_idx[:k]
    nearest_labels = y_train[nearest_idx]
    
    return np.bincount(nearest_labels).argmax()

In [45]:
print(predict_one(X_train, y_train, np.array([5.5, 5.5]), k=3))
print(predict_one(X_train, y_train, np.array([0.5, 0.5]), k=1))

1
0


In [51]:
def knn_predict(X_train, y_train, X_test, k):
    results = [predict_one(X_train, y_train, test_point, k) for test_point in X_test]
    return np.array(results)

In [52]:
from sklearn.datasets import load_iris
import numpy as np

data = load_iris()
X, y = data.data, data.target

rng = np.random.default_rng(42)
idx = rng.permutation(len(X))
split = int(0.8 * len(X))

train_idx, test_idx = idx[:split], idx[split:]
X_train, y_train = X[train_idx], y[train_idx]
X_test, y_test = X[test_idx], y[test_idx]

In [62]:
predictions = knn_predict(X_train, y_train, X_test, 3)
accuracy = (predictions == y_test).mean()
print(accuracy)
print(predictions.shape)
print(y_test.shape)

1.0
(30,)
(30,)
