In [2]:
import numpy as np

X_train = np.array([[0,0], [1, 0], [8,8], [9,7]])
y_train = np.array([-1, -1, 1, 1])
X_train = np.hstack((X_train, np.ones((len(X_train), 1))))
w = np.zeros(3)
print(X_train.shape)
print(w.shape)
print(X_train)

(4, 3)
(3,)
[[0. 0. 1.]
 [1. 0. 1.]
 [8. 8. 1.]
 [9. 7. 1.]]


In [3]:
x = X_train[0]
y = y_train[0]
mistake = y * (w @ x)
print(mistake)

-0.0


In [4]:
print(w)
w += y*x
print(w)

[0. 0. 0.]
[ 0.  0. -1.]


In [5]:
max_epochs = 100
w = np.zeros(3)
for epochs in range(max_epochs):
    m = 0
    for x, y in zip(X_train, y_train):
        mistake = y * (w @ x)
        if mistake <= 0:
            w += y*x
            m += 1
    print(m)        
    if m == 0:
        break
    

2
2
1
1
1
0


In [6]:
predictions = np.sign(X_train @ w)
print((predictions == y_train).mean())

1.0


In [7]:
def perceptron_fit(X_train, y_train, max_epochs):
    w = np.zeros(X_train.shape[1])
    converged = False
    for epochs in range(max_epochs):
        m = 0
        for x, y in zip(X_train, y_train):
            mistake = y * (w@x)
            if mistake <= 0:
                w += y*x
                m += 1
        if m == 0:
            converged = True
            break
    return w, converged

w, converged = perceptron_fit(X_train, y_train, 100)
print(w, converged)

[ 4.  8. -5.] True


In [9]:
def perceptron_predict(X_train, w):
    predictions = np.sign(X_train @ w)
    return predictions

predictions = perceptron_predict(X_train, w)
print(predictions)

[-1. -1.  1.  1.]
